config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  #get 'about', to: 'wellcome#about'

  #resources :articles
  #get "signup", to: "users#new"
  #resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    def index
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end
    
    def create
    
    end
    
    def destroy
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/chatroom.html.erb
<div>
  <h1 align="center">MessageMe</h1>
  <h2 align="center">ChatRoom</h2>
</div>

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
    <i class="circular orange coffee icon"></i>
    Say Something
</h4>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui small feed">
                    <div class="event">
                        <div class="content">
                            <div class="summary">
                                <a>Elliot Fu</a> added <a>Jenny Hess</a> as a friend
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="extra content">
               <form class="ui reply form">
                    <div class="field">
                        <div class="ui fluid icon input">
                            <input type="text" placeholder="Enter a message...">
                            <i class="bordered inverted orange icon edit"></i>
                        </div>
                    </div>
                </form> 
            </div>
        </div>
    </div>

    <div class="four wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui inverted vertical menu">
                    <a class="active item">
                        Home
                    </a>
                    <a class="item">
                        Messages
                    </a>
                    <a class="item">
                        Friends
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<%= link_to'Chatroom', root_path, class: "item" %>

<a class="item">
    Messages
</a>
<div class="right menu">
    <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
        <%= link_to'Log in', login_path, class: "item" %>
        <a class="item">Logout</a>
        <a class="item">Sign up</a>
    </div>
    </div>
    <div class="item">
        <div class="ui primary button">Sign Up</div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui inverted small menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>